@TimeClock.Api_HostAddress = http://localhost:5209

GET {{TimeClock.Api_HostAddress}}/weatherforecast/
Accept: application/json

### https://learn.microsoft.com/en-us/aspnet/core/test/http-files?view=aspnetcore-8.0
